### ISSUE TITLE
matrix-registration: alembic not building

### ISSUE THREAD

**Issue by D4ndellion** [ZerataX/nur-packages#2]
installing alembic fails for me with:
```
error: attribute 'matrix-registration' missing, at /nix/store/hah532ycf4aipmvja28mgfcnvpd36qd7-source/pkgs/matrix-registration/default.nix:57:7
(use '--show-trace' to show detailed location information)
```

**Comment by zeratax** [comment]
ehm when exactly does this happen? not sure how to replicate this

**Comment by zeratax** [comment]
https://matrix.to/#/!FSAZzdrsqMTyfaVUMF:dmnd.sh/$16178272968572gEehJ:dodsorf.as?via=dmnd.sh&via=matrix.org&via=hangout.lol
